@host = localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzM3Mzk3OTkwLCJleHAiOjE3Mzc0ODQzOTB9.RYxXnAb_AwTZwn1TF1pjYqI4ifm09z6asBMvPLCPNu0

### Register
POST http://{{host}}/auth/register
Content-Type: application/json

{
    "name": "Ifty",
    "username": "ifty",
    "email": "ifty64bit+1@gmail.com",
    "password": "123456"
}

### Login
POST http://{{host}}/auth/login
Content-Type: application/json

{
    "email": "ifty64bit@gmail.com",
    "password": "123456"
}

### Create Room
POST http://{{host}}/room/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "participants": [3, 2]
}

### Get List Of Rooms
GET http://{{host}}/room/list
Authorization: Bearer {{token}}

