@host = localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlN0ZXZlbiIsImVtYWlsIjoic3RldmVuQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTYxNjIwNjYwMn0.1

### Register
POST http://{{host}}/auth/register
Content-Type: application/json

{
    "name": "Ifty",
    "username": "ifty64bit",
    "email": "ifty64bit@gmail.com",
    "password": "123456"
}

### Login
POST http://{{host}}/auth/login
Content-Type: application/json

{
    "email": "ifty64bit@gmail.com",
    "password": "123456"
}

### Get List Of Rooms
GET http://{{host}}/room/list
Authorization: Bearer {{token}}

